name: Test application

on:
    pull_request:
    push:
        branches:
            - 'master'
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

# automatically cancel previously started workflows when pushing a new commit to a branch
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    php:
        name: "PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.1'
                      dependency-versions: 'lowest'
                      tools: 'composer:v1'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

                    - php-version: '8.0'
                      dependency-versions: 'highest'
                      tools: 'composer:v2'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: ${{ matrix.tools }}

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}

            - name: Execute test cases
              run: composer test
              env: ${{ matrix.env }}

    php-lint:
        name: "PHP Lint"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  tools: composer

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1

            - name: Lint code
              run: composer lint
